language: node_js
node_js:
  - "node"
install:
  - yarn install
script:
  - yarn build
  - yarn cover
  
# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
