language: node_js
node_js:
  - "node"
before_install:
  # Updating yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version
install:
  - yarn install
script:
  - yarn build
  - yarn lint
  - yarn cover
# Send coverage data to Coveralls
after_script:
  - "cat coverage/coverage.json | node_modules/.bin/remap-istanbul -t text-lcov | node_modules/coveralls/bin/coveralls.js"
